### DISCUSSION TITLE
Exposing public/authenticated dashboards outside of CDSDashboards

### DISCUSSION THREAD

**Discussion by costrouc** [nebari-dev/nebari#1238] [Ideas]
Wanted to detail a currently manual but good approach for scalably exposing dashboards external to jupyterhub. The motivation for this is the need for a long running, authenticated dashboard behind a custom url. QHub already has much of the foundation for this. Ideally in the future we will provide an extension mechanism to make this process easier and more integrated.

First step is to create a docker image and Kubernetes pod of the given dashboard/web server. In this example we will use the `traefik/whoami` service. This allows us to easily see the http headers (only for an example). Use your own dashboard here.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: dev
  labels:
    app: whoami
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          ports:
            - containerPort: 80
```

Next define a service that maps to this dashboard.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: dev
spec:
  selector:
    app: whoami
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
```

Finally we us traefik to do all the heavy lifting. There is a [middleware](https://doc.traefik.io/traefik/middlewares/overview/) using traefik forward auth which provides transparent authentication. In addition it sets the header `X-Forwarded-User`. Traefik will attempt to fetch certificates for any Host that you set. Also we have sticky sessions enabled! This allows for all requests from a given user to go to the same server every time. This allows stateful dashboards to operate properly.

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
  namespace: dev
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`quansight-beta.qhub.dev`) && PathPrefix(`/myownroute/`)
      middlewares:
        - name: traefik-forward-auth
          namespace: dev
      services:
        - name: whoami
          port: 80
          sticky:
            cookie:
              httpOnly: true
              name: whoami-sticky
              secure: true
              sameSite: None
```
