### DISCUSSION TITLE
How to handle an oversized instance for the general node_group?

### DISCUSSION THREAD

**Discussion by rsignell-usgs** [nebari-dev/nebari#1632] [Q&A]
I noticed that in our deployed Nebari instance deployed for ESIP on Amazon that we have:
```
  node_groups:
    general:
      instance: m5.2xlarge
      min_nodes: 1
      max_nodes: 1
    user:
      instance: m5.2xlarge
      min_nodes: 1
      max_nodes: 100
    worker:
      instance: m5.2xlarge
      min_nodes: 1
      max_nodes: 450
```
I'm not sure how we arrived at this, but I'm guessing this is definitely overkill for the `general` node_group and probably not optimal for the `worker` node_group.    I see that from [this section in the Nebari docs](https://www.nebari.dev/docs/troubleshooting#upgrade-the-instance-size-for-the-general-node-group) that's it is *not* a good idea to change the general node_group instance type by simply changing the config and redeploying.  

What would be the solution then in our case if we wanted to downgrade our general instance type (to reduce our always-on spend on AWS)?
