### DISCUSSION TITLE
Extending Server Lifetime

### DISCUSSION THREAD

**Discussion by jbouder** [nebari-dev/nebari#1733] [Q&A] [answered]
What is the best way to extend the lifetime of a server? Right now they seem to be shutting down after about 15 minutes of idle time. I tried adding the following to the nebari-config.yaml to extend to 1 hour, but it didn't seem to help:
```
jupyterhub:
  overrides:
    cull:
      timeout: 3600
```
Thanks!

**Comment by iameskild** [comment, marked as answer]
Hi @jbouder, I'm still working on docs for this update but in the meantime, I hope this helps. You can set any combination of the following settings (or none of them):

```yaml
jupyterlab:
  idle_culler:
    terminal_cull_interval: 5  # The interval (in minutes) on which to check for terminals exceeding the inactive timeout 
    terminal_cull_inactive_timeout: 15  # Inactive timeout (in minutes) before being culled  
    kernel_cull_interval: 5  # The interval (in minutes) on which to check for kernels exceeding the inactive timeout
    kernel_cull_idle_timeout: 15  # Inactive timeout (in minutes) before being culled 
    server_shutdown_no_activity_timeout: 15  # Shutdown the server after N minutes with no kernel or terminal
    kernel_cull_connected: true  # Whether to cull kernels that have multiple connections 
    kernel_cull_busy: false  # Whether to cull kernels that are currently busy (not recommended in most cases)
```
