### DISCUSSION TITLE
Jupyterlab spawned server properties

### DISCUSSION THREAD

**Discussion by gmaze** [nebari-dev/nebari#230] [Q&A] [answered]
hi !

## Question 1

I wonder **what are the possible values for the ``kubespawner_override`` properties that one can set in the ``qhub-config.yml`` file** ?

For instance, by default, I have

```yaml
profiles:
  jupyterlab:
  - display_name: Small Instance
    description: Stable environment with 1 cpu / 1 GB ram
    default: true
    kubespawner_override:
      cpu_limit: 1
      cpu_guarantee: 1
      mem_limit: 1G
      mem_guarantee: 1G
      image: quansight/qhub-jupyterlab:1abd4efb8428a9d851b18e89b6f6e5ef94854334
```

I added a new entry with these modifications:
```yaml
  - display_name: Larger Instance (Test)
    description: Stable environment with 2 cpu / 2 GB ram
    kubespawner_override:
      cpu_limit: 2
      cpu_guarantee: 2
      mem_limit: 2G
      mem_guarantee: 2G
      image: quansight/qhub-jupyterlab:1abd4efb8428a9d851b18e89b6f6e5ef94854334
```

but jupyterhub throws this when this server profile was spawned:

```
Event log
Server requested
2021-01-05 13:48:24+00:00 [Warning] 0/3 nodes are available: 1 Insufficient cpu, 2 node(s) didn't match node selector.
2021-01-05 13:48:26+00:00 [Normal] pod didn't trigger scale-up (it wouldn't fit if a new node is added): 1 max node group size reached, 2 Insufficient cpu
```
## Question 2

**Do the values of cpu/mem limits/guarantee are constrained by the image or by the ``worker`` or ``user`` instance set in the kubernetes nodes (I deployed on GCP)**

I modified the default values to:

```yaml
google_cloud_platform:
  project: <MY-PROJECT>
  region: us-central1
  zone: us-central1-c
  availability_zones:
  - us-central1-c
  kubernetes_version: 1.14.10-gke.31
  node_groups:
    general:
      instance: n1-standard-2
      min_nodes: 1
      max_nodes: 1
    user:
      instance: n1-standard-4
      min_nodes: 1
      max_nodes: 50
    worker:
      instance: n1-standard-2
      min_nodes: 1
      max_nodes: 100
```

but I don't have a clear understanding of the detailed interactions between the properties of nodes, pods, images, workers, etc ... throughout kubernetes, gcp, jupyterhub, dask...

thanks for your help/explanation !
