### DISCUSSION TITLE
Options to deploy Nebari to existing AWS VPC/subnets?

### DISCUSSION THREAD

**Discussion by mwengren** [nebari-dev/nebari#2559] [General]
We have some particular networking/security requirements that compel us to use a pre-existing VPC and associated public/private subnets in our AWS account.  Similarly, we can't create new InternetGateway (IGW) in our public subnet, we must use an existing networking setup for outgoing traffic out of AWS to our network or for any public traffic.

Is there a way to configure such a deployment by editing the nebari-config.yaml file appropriately?  Essentially to pass IDs for existing AWS resources (VPC, subnet, etc) for Nebari to deploy components to?  I can't find documentation for this type of deployment scenario in the Nebari [docs](https://www.nebari.dev/docs/welcome), so I assume it would require some manual editing of Nebari internals beyond just the options provided in nebari-config?

TIA!

**Comment by viniciusdc** [comment]
Hi @mwengren, Nebari supports existing AWS subnets, by passing the associated security group ID and existing subnet IDs in the `nebari-config.yaml`. However, I am not sure if Nebari even creates an IGW at all as part of its deployment process, so I guess it would default for any configuration already present in your infrastructure. 

Here's an example of how that can be set in the config: 
```
amazon_web_services:
  terraform_overrides:
    existing_subnet_ids: ["subnet-05b2b1f41f0b1d8a6", "subnet-017efc3309fbca2da"]
    existing_security_group_id: "sg-0e2c865bdd8824b1a"
  region: ...
  <other_attributes>: ...
```

I am c.c. @aktech @Adam-D-Lewis as both have more experience with AWS deployments, and Adam worked on adding support for this

**Reply by mwengren** [reply]
Thanks @viniciusdc Do you know if it's possible to deploy the Load Balancer in one subnet (our public subnet) and the k8s cluster and other resources like EFS in another (private) subnet?  

We have a small public subnet (/27) and a larger private subnet (/23).  Networking is provided between the two subnets via pre-configured Route Table.

**Reply by viniciusdc** [reply]
Unfortunately this is not supported, sorry I missed your ping

**Comment by mwengren** [comment]
@viniciusdc When I add the `terraform_overrides` YAML I get a validation error running `nebari deploy`:

```
ValidationError: 1 validation error for ConfigSchema
amazon_web_services.terraform_overrides
  Extra inputs are not permitted [type=extra_forbidden, input_value={'existing_subnet_ids': [... 'sg-xxxxxxxxxxxxxx'}, input_type=CommentedMap]
    For further information visit https://errors.pydantic.dev/2.4/v/extra_forbidden
```

Do I need a custom validation configuration as well?

**Comment by aktech** [comment]
The syntax is as following:

```yml
amazon_web_services:
  existing_subnet_ids:
    - subnet-xxxxxxxxxxxx
    - subnet-yyyyyyyyyyyy
  existing_security_group_id: sg-kkkkkkkkkkkk
```

**Reply by mwengren** [reply]
Thanks @aktech, I modified the formatting of my config file, but I am still getting the same validation error.

Config section:
```
amazon_web_services:
  terraform_overrides:
       existing_subnet_ids:
           - subnet-xxxxxxxxxxxxxxxx
           - subnet-yyyyyyyyyyyyyyy
        existing_security_group_id: sg-zzzzzzzzzzzzzzz
```

Output:
```
ValidationError: 1 validation error for ConfigSchema
amazon_web_services.terraform_overrides
  Extra inputs are not permitted [type=extra_forbidden, input_value={'existing_subnet_ids': [...net-xxxxxxxxxxxxxx']}, input_type=CommentedMap]
    For further information visit https://errors.pydantic.dev/2.4/v/extra_forbidden
```

Is it required to include two subnets?  What if I would like to deploy Nebari to only a single subnet? 

More accurately, I have a public/private subnet configuration (see details [above](https://github.com/orgs/nebari-dev/discussions/2559#discussioncomment-10034205)), but I don't know if this is an architecture that's supported by Nebari 'out of the box' or not?  We need the end-user access point (Load Balancer?) to be in our public subnet, and the k8s cluster in the private subnet, as we only have 16 IP addresses available in our public subnet. 



I have several other questions if you can assist:

What does passing an existing security group do?  I have a security group that manages permissions to our public subnet, so I planned to try passing that in hoping Nebari would adopt the same permissions rather than create a new permission set that is more open than I want.   

Are these terraform overrides documented anywhere or can you point me to the right section of the code to poke around to see what other override options are available, if any?
