### DISCUSSION TITLE
Unable to issue certificate from lets encrypt for my domain

### DISCUSSION THREAD

**Discussion by shauryagoel** [nebari-dev/nebari#2948] [Q&A] [answered]
I used this config to issue a proper certificate from let's encrypt-
```
certificate:
  type: lets-encrypt
  acme_email: <MY_EMAIL>
  # acme_server: https://acme-v02.api.letsencrypt.org/directory
  acme_server: https://acme-staging-v02.api.letsencrypt.org/director
```
But this is giving me the following error in traefik pod-
```
Unable to obtain ACME certificate for domains \"<MY_DOMAIN>\": unable to generate a certificate for the domains [<MY_DOMAIN>]: error: one or more domains had a problem:
[<MY_DOMAIN>] acme: error: 400 :: urn:ietf:params:acme:error:tls :: <IP>: remote error: tls: unrecognized name
" providerName=letsencrypt.acme ACME CA="https://acme-v02.api.letsencrypt.org/directory" routerName=dev-jupyterhub-ca277b77dd23830bef42@kubernetescrd rule="Host(`<MY_DOMAIN>`) && (Path(`/`) || PathPrefix(`/hub`) || PathPrefix(`/user`) || PathPrefix(`/services`))
```
I tried running it multiple times and with both staging and production server, but, still getting the same error. Can someone help me here to track the issue.
