### DISCUSSION TITLE
Keycloak themes

### DISCUSSION THREAD

**Discussion by verhulstm** [nebari-dev/nebari#2994] [Q&A]
How do i change the look for the keycloak login page?

**Comment by viniciusdc** [comment]
Hey @verhulstm, we've just included [this ability](https://github.com/nebari-dev/nebari/pull/2469) in the latest release `2025.3.1`. You need to include this section in your config:
```yaml
security:
  keycloak:
    initial_root_password: ***
    themes:
      enabled: true
      repository: https://github.com/****/keycloak-custom-theme
      branch: master
```

We don't have yet a template for the theme, its on the works, but you can achieve it following this:
- Create a public github repo, containing a folder with the name to your theme (e.g demo);
- Inside such folder copy over the contents from [keycloak/keycloak@main/themes/src/main/resources-community/theme/base](https://github.com/keycloak/keycloak/tree/main/themes/src/main/resources-community/theme/base) or use `my-cool-theme-name` example from [keycloak/keycloak-quickstarts@latest/extension/extend-admin-console](https://github.com/keycloak/keycloak-quickstarts/tree/latest/extension/extend-admin-console).
- In your nebari-config.yaml, make sure to correctly pass the URL for your github repo under the repository and branch fields.
- After deploying, go to the Keycloak UI and select your new theme
