### DISCUSSION TITLE
adding additional pages and sub-sites to nebari

### DISCUSSION THREAD

**Discussion by verhulstm** [nebari-dev/nebari#2997] [Q&A]
do you have a recommended way for users/developers to create fully custom flask/django sites and authenticate their user logins with nebari's keycloak?

**Comment by marcelovilla** [comment]
The recommended way to do this is to make use of [Nebari's plugin system](https://www.nebari.dev/docs/how-tos/nebari-extension-system/). Furthermore, you'll probably need to deploy your service in the k8s cluster, so using a Helm chart would be a good option. You can see a good example of this, including Keycloak interaction in the [Nebari Self Registration plugin](https://github.com/nebari-dev/nebari-self-registration).

Let me know if this helps!

**Comment by viniciusdc** [comment]
Just to provide a more in-depth explanation, here are some considerations:

1. **Quick Sharing within Nebari (Development or Presentation Purposes)**  
   If the main objective is to temporarily share a running application, notebook, or dashboard with others (e.g., for development or presentation), then leveraging [jhub-apps](https://www.nebari.dev/docs/how-tos/jhub-app-launcher) can be a fast, straightforward solution. This route usually involves:
   - Launching the app from JupyterHub within your Nebari instance.
   - Quickly deploying a test version for others to interact with, without worrying too much about production-level requirements.

2. **Long-Running Production/Development Application (HA, Scaling, etc.)**  
   If you need the benefits of a Kubernetes cluster (high availability, scalability, and so on), then the recommended approach is to treat your application as a Nebari “service.” Essentially, any Nebari service is comprised of these Kubernetes objects:
   - `IngressRoute` (Handles external traffic routing)
   - `Kubernetes Service` (Abstracts the application as a service)
   - One or more target pods/containers (Where your application actually runs)

   You can provide these objects in two main ways:
   1. **Creating a plugin** that injects and manages these deployment objects directly into the Nebari deploy as a stage. Just so you know, you can check out these [example plugins](https://github.com/nebari-dev/nebari-plugin-examples/tree/main/examples).
   2. **Using the `helm_extension` mechanism** or manually deploying a Helm chart. This approach involves dropping a Helm chart into your Nebari configuration and allowing Nebari to deploy it alongside other services.

   In many cases, **the Helm approach is simpler**, especially if you’re already familiar with Helm, or you just want to experiment without writing a full plugin.

### Quick Helm Example

If you want to prototype a base application in Nebari via Helm:

1. **Install the Helm client** on your local machine. (See the official Helm install instructions: [https://helm.sh/docs/intro/install/](https://helm.sh/docs/intro/install/))
2. **Create a Helm chart directory** within your Nebari project:
   ```bash
   helm create poc-application
   ```
   This will generate a scaffold with files like:
   ```
   poc-application
   ├── Chart.yaml
   ├── charts
   ├── templates
   │   ├── NOTES.txt
   │   ├── _helpers.tpl
   │   ├── deployment.yaml
   │   ├── hpa.yaml
   │   ├── ingress.yaml
   │   ├── service.yaml
   │   ├── serviceaccount.yaml
   │   └── tests
   │       └── test-connection.yaml
   └── values.yaml
   ```
3. **Customize the templates** (e.g., `deployment.yaml`, `service.yaml`, `ingress.yaml`) to suit your application’s needs.

4. **Configure your Nebari deployment** to include this Helm chart under the [Helm Extensions](https://www.nebari.dev/docs/explanations/custom-overrides-configuration#helm-extensions) stage or deploy it manually with `helm install` if you’re just testing.

This approach lets you use the Kubernetes cluster’s built-in features (scaling, updating, monitoring, etc.) without manually creating each Kubernetes object. Once it is running, you’ll see your new “service” under the Nebari cluster, accessible via the `IngressRoute` you specify in the `templates/ingress.yaml`.


For example, below is a few custom values for the values.yaml file to run a ngix application on Nebari:

```yaml
replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "stable"

service:
  type: ClusterIP
  port: 80
```

you will need to replace the current ingress.yaml under templates to this one instead:
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`<YOUR-NEBARI-DOMAIN>`) && PathPrefix(`/<YOUR-ENDPOINT-PREFIX>/`)
    services:
    - name: {{ include "poc-app.fullname" . }}
       port: {{ $.Values.service.port }}
```

and in your nebari config file include:
```yaml
helm_extensions:
  - name: poc-app
    chart: /home/.../nebari/poc-app
    repository: ""
    version: <SAME-VERSION-UNDER-CHART.YAML>
```
