### DISCUSSION TITLE
the plugin "nebari-self-registration" gives pydantic validation errors for ConfigSchema

### DISCUSSION THREAD

**Discussion by verhulstm** [nebari-dev/nebari#3080] [Community]
nebari: ValidationError: 2 validation errors for ConfigSchema
    nebari: self_registration.affinity.selector.SelfRegistrationAffinitySelectorConfig.defau
    nebari: lt
    nebari:   Field required [type=missing, input_value={'app': 'nodegroup_a', 'job':
    nebari: 'nodegroup_b'}, input_type=CommentedMap]
    nebari:     For further information visit https://errors.pydantic.dev/2.11/v/missing
    nebari: self_registration.affinity.selector.str
    nebari:   Input should be a valid string [type=string_type, input_value={'app':
    nebari: 'nodegroup_a', 'job': 'nodegroup_b'}, input_type=CommentedMap]
    nebari:     For further information visit https://errors.pydantic.dev/2.11/v/string_type

**Comment by verhulstm** [comment]
the issue seems to come from the affinity section 

```
  affinity:
    enabled: true
    selector:
      app: nodegroup_a
      job: nodegroup_b
```

**Reply by viniciusdc** [reply]
Hey @verhulstm the issue is that nebari-self-registration has its own schema that differs from the general one under nebari at least for the affinity structure. You can glance over if here: https://github.com/nebari-dev/nebari-self-registration/blob/main/src/nebari_plugin_self_registration/__init__.py#L26

basicaly the problem is that the selector only accepts one node reference.

**Reply by viniciusdc** [reply]
so you need to pass
```yaml
affinity:
    enabled: true
    selector: nodegroup_a
```
