### DISCUSSION TITLE
What dask pins does qhub require?

### DISCUSSION THREAD

**Discussion by kcpevey** [nebari-dev/nebari#313] [Q&A] [answered]
I had been using the following pins for my qhub envs:
```
  - dask-gateway==0.6.1
  - dask==2.14.0
  - distributed==2.14.0
  - python-blosc==1.9.1
```
Is this still the required set of pins?

**Comment by rsignell-usgs** [comment]
@kcpevey, I think questions here on discussions unfortunately don't show up on the radar screens of quansight folks.   

I think it's good to use discussion for these sorts of questions, but then perhaps we should post the discussion link on the[ Qhub Gitter](https://gitter.im/Quansight/qhub) to get attention.

**Reply by laisbsc** [reply]
> Is this still the required set of pins?
@aktech @tylerpotts do we know the answer to Kim's question?

**Reply by aktech** [reply]
Yup, see the note below Environments here:
https://github.com/Quansight/qhub-cloud/blob/main/docs/docs/gcp/configuration.md#environments

**Reply by kcpevey** [reply]
Hey @rsignell-usgs! Thanks for letting me know and for bumping the question so I could get an answer! I'm working with @dharhas at Quansight these days. I'll raise the issue of keeping up with this board - I think it's important for the community :)

**Comment by tylerpotts** [comment, marked as answer]
@rsignell-usgs The best way to manage dask pins now is to use the `qhub-dask` metapackage from conda-forge. Usage will look like this:

```
environments:
  environment-dask.yaml:
    name: dask
    channels:
    - conda-forge
    dependencies:
    - python
    - ipykernel
    - ipywidgets
    - qhub-dask ==0.2.3
```

The pins for the metapackage can be found in the conda-forge recipe here: https://github.com/conda-forge/qhub-dask-meta-feedstock/blob/master/recipe/meta.yaml
