### DISCUSSION TITLE
Failure upgrading from 0.3.11 to 0.3.12

### DISCUSSION THREAD

**Discussion by rsignell-usgs** [nebari-dev/nebari#841] [Q&A]
We tried to follow the [Qhub upgrade instructions](https://docs.qhub.dev/en/latest/source/admin_guide/upgrade.html?highlight=upgrade) to advance from 0.3.11 to 0.3.12 on a development deployment of Qhub (not the ESIP qhub).

After making the changes to 2 files (see screenshot below), the Github Action failed in "Render Changes to Template" step with:
```
Run qhub render -c qhub-config.yaml
Error: The schema validation of the qhub-config.yaml failed. The following error message may be helpful in determining what went wrong:

1 validation error for Main
default_images -> conda_store
  field required (type=value_error.missing)
Error: Process completed with exit code 1.
```
The changes we made that triggered the error are shown here: 

![2021-10-07_15-39-48](https://user-images.githubusercontent.com/1872600/136482363-c4680f4f-ac8e-4f95-999f-fe1590eb67ef.png)

What did we do wrong?   

What does `value_error.missing` mean?  
Is there a new parameter we need to include now?

We could provide access to the private repo if desired.

**Comment by tylerpotts** [comment]
@rsignell-usgs It looks like a new required value was added to the `default_images` key. Try adding the `conda_store` image as seen below:

```yaml
default_images:
  jupyterhub: quansight/qhub-jupyterhub:v0.3.12
  jupyterlab: quansight/qhub-jupyterlab:v0.3.12
  dask_worker: quansight/qhub-dask-worker:v0.3.12
  dask_gateway: quansight/qhub-dask-gateway:v0.3.12
  conda_store: quansight/qhub-conda-store:v0.3.12
```
