### ISSUE TITLE
[ENH] - Add `local` support for Mac

### ISSUE THREAD

**Issue by iameskild** [nebari-dev/nebari#1405]
### Feature description

It would be nice, as developers, to develop on Mac (and Windows) using a `local` (kind) deployment.

### Value and/or benefit

Currently `local` deployments are only available for Linux. Adding this would allow those with Macs to develop and prototype more quickly the current workarounds ([see dev docs](https://docs.qhub.dev/en/latest/source/dev_guide/minikube.html#minikube-on-aws)). 

### Anything else?

Affects all Macs (Apple Silicon + Intel).

**Comment by iameskild** [comment]
I am currently able to partially deploy on Mac ([see branch `kind_on_mac`](https://github.com/Quansight/qhub/tree/kind_on_mac)). Unfortunately this solution is only partially and quite "hacky". More work will be needed before this is fully usable.

**Comment by iameskild** [comment]
So far I have tried (or researched) the following with no success:
- UTM virtual machine
- virtualbox virtual machine
  - last time I was reading about this, it wasn't possible to run on Apple Silicon (M1/M2) macs but this [might have changed ](https://osxdaily.com/2022/10/22/you-can-now-run-virtualbox-on-apple-silicon-m1-m2/)and I will need to give this another try.

**Comment by kcpevey** [comment]
Blocked by #1950

**Comment by marcelovilla** [comment]
The issue around Nebari not working locally on a `kind` cluster on macOS/Windows stems from the fact that Docker containers are not executed natively but rather in a VM. Thus, the container networks are not exposed and cannot be reached from the host.

There are a couple of options we can try to be able to deploy Nebari locally on macOS/Windows:

* Configure [Extra Port Mappings](https://kind.sigs.k8s.io/docs/user/configuration/#extra-port-mappings) to port forward the relevant nodes (probably the load balancer) and configure an [Ingress Controller](https://kind.sigs.k8s.io/docs/user/configuration/#extra-port-mappings) using traefik.
* Try a tool like https://github.com/chipmk/docker-mac-net-connect, which allows for direct connections to the containers via their IP address.

**Comment by viniciusdc** [comment]
seems interesting as an option with Vagrant and Kubernetes https://ugurakgul.medium.com/creating-a-local-kubernetes-cluster-with-vagrant-ba591ab70ee2

**Comment by viniciusdc** [comment]
from @dcmcand https://github.com/techiescamp/vagrant-kubeadm-mac-silicon

**Comment by aktech** [comment]
I have got it working on my Mac M1. Here are the docs: https://github.com/nebari-dev/nebari-docs/pull/454

<img width="1920" alt="Screenshot 2024-05-08 at 3 09 16 pm" src="https://github.com/nebari-dev/nebari/assets/5647941/7c9ba32f-98ad-41fe-989a-e2b4276b9ce8">
<img width="1920" alt="Screenshot 2024-05-08 at 3 09 37 pm" src="https://github.com/nebari-dev/nebari/assets/5647941/6fce4b06-4544-46c8-bb69-51cf177ebea1">
<img width="1920" alt="Screenshot 2024-05-08 at 3 09 02 pm" src="https://github.com/nebari-dev/nebari/assets/5647941/5cbfb02f-8a40-48e1-94d1-78a69233ae39">





This what my nebari config looks like:

```yaml
provider: local
namespace: dev
nebari_version: 2024.5.1rc1
project_name: local-dev
domain: nebari.iakte.ch
ci_cd:
  type: none
terraform_state:
  type: remote
security:
  keycloak:
    initial_root_password: <SANITIZED>
    overrides:
      image:
        repository: quay.io/aktech/keycloak
        tag: 15.0.2
  authentication:
    type: password

default_images:
  jupyterhub: quay.io/nebari/nebari-jupyterhub:m1-image
  jupyterlab: quay.io/nebari/nebari-jupyterlab:m1-image
  dask_worker: quay.io/nebari/nebari-dask-worker:m1-image

jhub_apps:
  enabled: true

argo_workflows:
  enabled: false

conda_store:
  image: quay.io/aktech/conda-store-server
  image_tag: sha-558beb8
theme:
  jupyterhub:
    hub_title: Nebari - local-dev
    welcome: Welcome! Learn about Nebari's features and configurations in <a href="https://www.nebari.dev/docs/welcome">the
      documentation</a>. If you have any questions or feedback, reach the team on
      <a href="https://www.nebari.dev/docs/community#getting-support">Nebari's support
      forums</a>.
    hub_subtitle: Your open source data science platform, hosted
certificate:
  type: lets-encrypt
  acme_email: <SANITIZED>
```

Relevant issues:
- https://github.com/nebari-dev/nebari/issues/2454
- https://github.com/conda-incubator/conda-store/issues/821

Relevant PRs:
- https://github.com/nebari-dev/keycloak-containers/pull/1
- https://github.com/nebari-dev/nebari-docker-images/pull/141
- https://github.com/nebari-dev/nebari-docs/pull/454
