### ISSUE TITLE
[ENH] - Disable generating .gitlab-ci.yml in Gitlab CI

### ISSUE THREAD

**Issue by kalpanachinnappan** [nebari-dev/nebari#1537]
### Feature description

Disable generating specifically the `.gitlab-ci.yml` file, for those who are managing their Nebari installation in Gitlab CI with **custom** `scripts` sections in CI.

**Suggestion**: Set a variable like `ci_render` in `nebari-config.yaml`, like:

```
ci_cd:
  type: gitlab-ci
  branch: main
  commit_render: true
  ci_render: false
```

This way CI would still render other files to be committed (`.tf` files, etc), but **will not** generate and commit back the `.gitlab-ci.yml` file.

### Value and/or benefit

Beneficial for those who require custom `scripts` sections in `.gitlab-ci.yml`, for example:

- specifying their own `git config user.email` and `git config user.name`
- adding extra scripts like `git remote set-url origin https://user:$TOKEN@gitlab.com/group/nebari`

Disabling the generation of `.gitlab-ci.yml` will allow teams to maintain their own CI configuration.

**Comment by iameskild** [comment]
Hi @kalpanachinnappan, thanks for reaching out. I'm not sure if this fully addresses your enhancement request but for deployments that use GitLab-CI, you can add `before_script` or `after_script` to the `ci_cd` section of `nebari-config.yaml`  like this ([see our old docs](https://docs.qhub.dev/en/latest/source/installation/configuration.html?highlight=gitlab-ci#continuous-integration-and-continuous-deployment)):

```yaml
ci_cd:
  type: gitlab-ci
  branch: main
  commit_render: true
  before_script:
    - echo "running commands before ci completes"
  after_script:
    - echo "running commands after ci completes"
    - echo "additional commands to run"
 ```

Let us know if this make any difference :)

**Comment by dharhas** [comment]
@iameskild lets make sure to migrate those instructions to the new docs.

**Comment by kalpanachinnappan** [comment]
@iameskild The before and after scripts would not work for modifying the main `script` section though, for example setting the git username/email details:

```
"git config user.email 'nebari@quansight.com'",
"git config user.name 'gitlab ci'",
```

If I set these to our custom values in `before_script`, the main `script` section would just overwrite the `before_script`, right?

**Comment by iameskild** [comment]
Hi @kalpanachinnappan as far as I am aware, the actions in the `before_script` are prepended to the `script`  section.

> Scripts you specify in before_script are concatenated with any [script](https://docs.gitlab.com/ee/ci/yaml/#script)s you specify in the main script. The combined scripts execute together in a single shell.

Source [GitLab-CI docs](https://docs.gitlab.com/ee/ci/yaml/#before_script)

The same cannot be said for the `after_script`, source [GitLab-CI docs](https://docs.gitlab.com/ee/ci/yaml/#after_script).

I have seen other deployments add their git user.email and user.name to the `before_script` in the way you describe. You might need to include a `git remote set-url ...`

```yaml
ci_cd:
  type: gitlab-ci
  branch: main
  before_script:
  - git remote set-url origin https://gitlab-ci-token:${CI_PUSH_TOKEN}@gitlab.com/<org>/<team>/<repo>.git
  - git config --global user.email '<email>'
  - git config --global user.name '<username>'
```

--- 

I might need some more context to answer the second question about removing the entire `script` section. If that's the case, the GitOps workflow will obviously no longer work. Do you have another GitLab-CI pipeline that want to use to handle the redeployment instead?
