### ISSUE TITLE
[BUG] - Configure conda-store allowed channels via nebari config

### ISSUE THREAD

**Issue by alimanfoo** [nebari-dev/nebari#1594]
### Describe the bug

I'd like to configure the [CondaStore.conda_allowed_channels](https://conda.store/en/latest/administration.html?highlight=channel#conda-store-server-app-condastore) via the nebari configuration file. This should be possible as described [here](https://github.com/nebari-dev/nebari/discussions/1567#discussioncomment-4267160):

```
conda_store:
  extra-settings:
     CondaStore:
       conda_allowed_channels = []
```

However, this does not validate according the nebari scheme, which requires "extra_settings". 

Trying this configuration instead:

```
conda_store:
  extra_settings:
     CondaStore:
       conda_allowed_channels = []
```

...does validate but may result in a broken conda-store service.

### Expected behavior

In general any configuration parameter should be possible to pass through to conda-store via nebari-config.yaml.

### OS and architecture in which you are running Nebari

GKE

### How to Reproduce the problem?

Try the example configs given above and deploy.

### Versions and dependencies used.

Nebari version 2022.11.1.

### Compute environment

GCP

### Integrations

conda-store

### Anything else?

Originally discussed here: https://github.com/nebari-dev/nebari/discussions/1567.
