### ISSUE TITLE
[BUG] - Version inconsistency with s3fs/boto in default dask env

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari#1638]
### Describe the bug

There is a version inconsistency between s3fs and boto in the default dask env. Most updated environments seem to resolve this properly on their own but we have one that did not. This makes s3fs access fail. 

Reproducer:
```
import fsspec
fs = fsspec.filesystem('s3', anon=True)
fs.ls('noaa-nwm-retro-v2-zarr-pds')
```

Error:

```
File /home/conda/nebari-git/2530054aaae017bb0e7cad39471b7d12db7a8014516f8e46a581318ae003fc9b-20221031-224345-235874-2-dask/lib/python3.9/site-packages/aiobotocore/client.py:82, in AioClientCreator.create_client(self, service_name, region_name, is_secure, endpoint_url, verify, credentials, scoped_config, api_version, client_config)
     72 self._register_eventbridge_events(
     73     service_client, endpoint_bridge, endpoint_url
     74 )
     75 self._register_s3_events(
     76     service_client,
     77     endpoint_bridge,
   (...)
     80     scoped_config,
     81 )
---> 82 self._register_s3_control_events(
     83     service_client,
     84     endpoint_bridge,
     85     endpoint_url,
     86     client_config,
     87     scoped_config,
     88 )
     89 self._register_endpoint_discovery(
     90     service_client, endpoint_url, client_config
     91 )
     92 return service_client

TypeError: _register_s3_control_events() takes 2 positional arguments but 6 were given
```

These versions caused the error above:
botocore	1.27.59
aiobotocore	2.4.0
s3fs	2022.10.0

These versions work:
botocore	1.27.59
aiobotocore	2.4.0
s3fs	2022.11.0

I propose to pin the dask env in the config file to 

```
    name: dask
    channels:
    - conda-forge
    dependencies:
    - python=3.10.8
    - ipykernel=6.21.0
    - ipywidgets=7.7.1
    - nebari-dask=2023.1.1
    - python-graphviz=0.20.1
    - pyarrow=10.0.1
    - s3fs=2023.1.0 
    - gcsfs=2023.1.0
    - numpy=1.23.5 
    - numba=0.56.4
    - pandas=1.5.3
    - pip:
      - kbatch==0.4.1
```

I've confirmed this works with several dask examples and is able to access s3 properly.

### Expected behavior

I expect Dask and s3fs to work in the default dask environment.

### OS and architecture in which you are running Nebari

?

### How to Reproduce the problem?

See above.

### Compute environment

GCP
