### ISSUE TITLE
Research a method of increasing the storage size of `/dev/shm`

### ISSUE THREAD

**Issue by iameskild** [nebari-dev/nebari#1642]
We have run into a `No space left on device` error that appears to be due to the limited amount of space on the `/dev/shm` (shared memory) drive. 

I was expecting this change to the `kubespawner_overrides` would do the trick.

https://github.com/nebari-dev/demo-nebari-dev/pull/12

**Comment by costrouc** [comment]
This was completed via

```yaml
      extra_pod_config:
        volumes:
        - name: "dshm"
          emptyDir:
            medium: "Memory"
            sizeLimit: "2Gi"
      extra_container_config:
        volumeMounts:
        - name: "dshm"
          mountPath: "/dev/shm"
```

In the profile. `
