### ISSUE TITLE
[ENH] - Ability to set environment variables on conda-store worker

### ISSUE THREAD

**Issue by costrouc** [nebari-dev/nebari#1643]
### Feature description

Sometimes you need to be able to set environment variables on the conda-store worker. E.g. https://conda-forge.org/docs/user/tipsandtricks.html#installing-cuda-enabled-packages-like-tensorflow-and-pytorch.

Currently have been doing manually

```yaml
envs:
  - name: CONDA_OVERRIDE_CUDA
    value: "11.8"
````

### Value and/or benefit

Can build gpu environments
