### ISSUE TITLE
Potential issues when using Dask-Gateway with multiple simultaneous users

### ISSUE THREAD

**Issue by iameskild** [nebari-dev/nebari#1750]
During the recent PyCon Nebari tutorial, we had 30+ people trying to connect to the Dask-Gateway cluster at the same time. Some users were able to connect and others were not. Those who were not able to connect ran into the following error message:

```
ClientConnectorError: Cannot connect to host nebari-dask-gateway-gateway-api.dev:8000 ssl:default [Connect call failed ('10.35.246.207', 8000)]
```

Based on the CPU/memory limits the Dask-Gateway pod has by default, it might be a resource limitation. Another possible guess is that the Dask-Gateway API was simply overwhelmed. We need to investigate further to isolate what the root cause of this issue might be.

**Comment by dharhas** [comment]
@iameskild @rsignell-usgs 

What does the ESIPFed cluster use for the dask-gateway pod? Is it the same as default? Have they seen this issue before?

**Comment by rsignell-usgs** [comment]
Thanks for the heads up on this issue @dharhas.   We have not seen this issue on the ESIP Nebari deployment, but we also haven't had 50 people all try to launch a cluster at the same time.    I thought I remembered that someone (the Berkeley Jupyter team?) tested with 1000 users, all with Dask clusters on Dask Gateway though.   Perhaps I'm mistaken?   @yuvipanda ?

The configuration for the Nebari deployment is: 
``` yaml
  node_groups:
    general:
      instance: m5.2xlarge
      min_nodes: 1
      max_nodes: 1
    user:
      instance: m5.2xlarge
      min_nodes: 1
      max_nodes: 100
    worker:
      instance: m5.2xlarge
      min_nodes: 1
      max_nodes: 450
```
