### ISSUE TITLE
terraform Error: Error creating S3 bucket: AuthorizationHeaderMalformed: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-2'

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/nebari#1825]
This error occurs on some AWS Nebari deployments when the terraform state is set to "remote".  This occurs b/c a s3 bucket is created based on the deployment name (name section in nebari-config.yaml) to store the terraform state, however s3 bucket names must be globally unique.  There are a few possible workarounds here:
1) Change the name of the deployment to something more unique
2) Set the terraform state to local (not ideal)

As a longer term solution, perhaps we can give a better error message and also allow for some way to override the s3 bucket name that is created for the terraform remote state. e.g.
```yaml
# nebari-config.yaml
...
amazon_web_services:
  terraform_state_s3_bucket: <unique-bucket-name>
...
```
