### ISSUE TITLE
[EXP] Exploration on Oauth2-proxy for traefik-forwardauth replacement

### ISSUE THREAD

**Issue by viniciusdc** [nebari-dev/nebari#1829]
### What is Traefik forward-auth and where it's currently being used on Nebari?
[Traefik forward-auth](https://doc.traefik.io/traefik/middlewares/http/forwardauth/) is a middleware component used with Traefik, a popular reverse proxy and load balancer. It is designed to handle authorization requests by redirecting them to an external authentication service. Traefik forward-auth is currently being utilized to redirect authorization requests to Keycloak, which acts as the identity provider and performs the user access validation.

It's important to note that Traefik forward-auth itself does not handle the authentication process. Instead, it serves as a middleware to redirect authorization requests to the external authentication service (Keycloak in this case) and then captures the necessary user-authenticated headers, such as tokens or session information. These headers are then added to the original request before forwarding it to the protected backend services (any useful app that is currently exposed in the main hub).

Some of the services using it:
- Dask-gateway (any client-to-server communication outside the cluster passes over this middleware)
- CDSdashboards
- ClearML**
- Any service deployed from within the helm extension mechanism, that would like to benefit from the existing Keycloak OIDC layer

### What is oauth2-proxy, and how can it be a good replacement? 
[oauth2-proxy](https://oauth2-proxy.github.io/oauth2-proxy/), on the other hand, is a complete authentication proxy that handles both the authentication and authorization processes. It integrates with OAuth2 providers like Google, GitHub, or Azure, and handles the entire authentication flow, including user login, token retrieval, and session management.

### What are the main benefits of replacing it?
Compared to Traefik forward-auth, oauth2-proxy offers a more comprehensive authentication solution. It not only redirects authorization requests but also handles the complete authentication process, providing Single Sign-On (SSO) capabilities and supporting multiple OAuth2 providers. Additionally, oauth2-proxy provides advanced features such as access control, fine-grained permissions, and easy integration with existing OAuth2 workflows. So we would have fine-grained control over access to certain services by fully utilizing the group memberships and roles coming from Keycloak (or any supported provider) 

One significant benefit of using oauth2-proxy as a replacement for Traefik forward-auth is the decoupling of the authentication burden from the application itself. By implementing oauth2-proxy as a sidecar container or service, the application becomes completely oblivious to any authentication logic. Instead, the application will "talk-to-itself" by requests to the current layer endpoints information for the current user: such as "Is the user authenticated?" and "Which roles, and permissions does this user have?"

This decoupling simplifies the application development process and improves maintainability. The application no longer needs to handle authentication-related concerns, such as validating tokens, managing sessions, or integrating with multiple OAuth2 providers. Instead, it can rely on oauth2-proxy to handle these tasks, allowing the core functionality of the application to be much less robust or restricted by a certain authentication provider/logic.

This is, It ensures that the authentication process remains consistent and secure, regardless of the individual application implementations.

### Integration technical details: How it works

To implement oauth2-proxy as a sidecar container alongside the application container in the same pod, the following is an overview of how it works:

1. Create a Kubernetes Pod with two containers: the oauth2-proxy container and the application container. These containers will share the same network namespace and can communicate with each other internally using `localhost` ports. (based on Oauth2 proxy upstream configuration)

2. Configure the ingress controller, Traefik, to route incoming requests to the oauth2-proxy container first. The oauth2-proxy container will handle the authentication and authorization flow.

3. The oauth2-proxy container should be configured with the necessary OAuth2 provider details, such as client ID, client secret, and redirect URL. This allows the container to initiate the authentication process with the provider. (Keycloak)

4. When an incoming request reaches the oauth2-proxy container, it checks if the user is already authenticated. If not, the container redirects the user to the OAuth2 provider's login page.

5. Once the user successfully authenticates with the provider, the oauth2-proxy container receives the authorization callback. It then retrieves the user's tokens or session information back to the client.

6. The oauth2-proxy container forwards the request to the application container using its internal communication within the pod.

7. The application container processes the request as usual, utilizing the information provided by the oauth2-proxy container for authentication and authorization. Such as requesting user information by querying any [extra endpoints](https://oauth2-proxy.github.io/oauth2-proxy/docs/features/endpoints)

### Bellow a sketch diagram of the authentication flux (for a sidecar integration)
![Blank diagram (2)](https://github.com/nebari-dev/nebari/assets/51954708/4f37d924-e9cf-4f32-8062-0b7be5b63e25)

### Demo example:

```yaml
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: test-oauth2-route
  namespace:
spec:
  routes:
    - match: Host(`myhost.domain`) && PathPrefix(`/test`)
      kind: Rule
      services:
        - name: oauth2-proxy
          namespace: dev
          port: 4180
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oauth2-proxy
  name: oauth2-proxy
  namespace: dev
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4180
      protocol: TCP
      targetPort: 4180
    - name: app
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    k8s-app: oauth2-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
        - args:
            - --provider=keycloak-oidc
            - --oidc-issuer-url=https://myhost.domain/auth/realms/nebari
            - --email-domain=*
            - --scope=openid
            - --upstream=http://127.0.0.1:8000/ # upstream port for you expose app
            - --http-address=0.0.0.0:4180 # exposed port for the proxy, will be used by the service for communication
            - --reverse-proxy=true # used when behind a proxy layer like Traefik
            - --set-xauthrequest=true # Needed when behind a proxy to ensure the headers are forwarded back and forth from the client
            - --proxy-prefix=/test/oauth2
            - --redirect-url=https://myhost.domain/test/oauth2/callback
            - --skip-provider-button=true # to avoid Oauth2 OIDC provider selection page, redirects directly to keycloak login page
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              value: <name-keycloak-client>
            - name: OAUTH2_PROXY_CLIENT_SECRET
              value: <secret-keycloak-client>
            - name: OAUTH2_PROXY_COOKIE_SECRET
              value: aksjdhfakjshdfkahsdkjfkdsfhaksjd # Anything here, needs to be 64bytes (around that)
            - name: OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL
              value: "true"
            - name: WHITELIST_DOMAINS
              value: domain 
          image: quay.io/oauth2-proxy/oauth2-proxy:latest
          imagePullPolicy: Always
          name: oauth2-proxy
          ports:
            - containerPort: 4180
              protocol: TCP
        - name: myapp
          image: vcerutti/helloworld-python:latest # your app image for the container 
          imagePullPolicy: Always
          ports:
            - containerPort: 8000 # exposed app port
              protocol: TCP
              name: server
```
