### ISSUE TITLE
[BUG] - nebari upgrade prompts for image tag upgrade excessively

### ISSUE THREAD

**Issue by sblair-metrostar** [nebari-dev/nebari#1960]
### Describe the bug

Running `nebari upgrade ...` on a file that includes match image tags will prompt the user separately to upgrade each image tag found for each upgrade step incurred. For example, upgrading from 2023.4.1 to 2023.7.2 with `default_images` and custom `profiles[].kubespawner_override` fields can result in 8 or more y/n prompts. The final version is the only one that matters in this context, and its arguable that the individual images are also redundant. These prompts should be minimized.

### Expected behavior

1. Only prompt to upgrade to the final image in the upgrade path, skipping intermediate steps.
2. Maybe just assume a single y/n is sufficient to upgrade them all, rather than individually.

### OS and architecture in which you are running Nebari

Ubuntu Linux, x64

### How to Reproduce the problem?

Run `nebari upgrade -c nebari-config.yaml` with something resembling the following in the file.

``` yaml
default_images:
  jupyterhub: quay.io/nebari/nebari-jupyterhub:2023.4.1
  jupyterlab: quay.io/nebari/nebari-jupyterlab:2023.4.1
  dask_worker: quay.io/nebari/nebari-dask-worker:2023.4.1
profiles:
  jupyterlab:
  - display_name: test
    kubespawner_override:
      image: quay.io/nebari/nebari-jupyterlab:2023.4.1
```

![image](https://github.com/nebari-dev/nebari/assets/70233904/fb5f8c4c-efd8-4021-b432-94a4ae9d0e65)

### Versions and dependencies used.

Nebari: 2023.7.2.dev

### Compute environment

None
