### ISSUE TITLE
[BUG] - nebari upgrade incorrect image matching on profiles.dask_worker

### ISSUE THREAD

**Issue by sblair-metrostar** [nebari-dev/nebari#1961]
### Describe the bug

`nebari upgrade` is incorrectly expecting the `profiles.dask_worker` section to have a `kubespawner_override` subsection for image tag updates. Per the schema, the `image` value should be at the top level of the named profile.

### Expected behavior

Command should successfully upgrade any matching image tags included in the `profiles.dask_worker` section to the current release.

### OS and architecture in which you are running Nebari

Ubuntu Linux, x64

### How to Reproduce the problem?

Run `nebari upgrade -c nebari-config.yaml` on a file with something like the following present:

Image will be found in the following (incorrect) yaml:
``` yaml

profiles:
  dask_worker:
    test:
      kubespawner_override:
        image: quay.io/nebari/nebari-jupyterlab:2023.4.1

```

Image will be missed in the following (correct) yaml:
``` yaml

profiles:
  dask_worker:
    test:
      image: quay.io/nebari/nebari-jupyterlab:2023.4.1

```

### Versions and dependencies used.

Nebari: 2023.7.2.dev

### Compute environment

None
