### ISSUE TITLE
[BUG] - nebari upgrade doesn't match -gpu images

### ISSUE THREAD

**Issue by sblair-metrostar** [nebari-dev/nebari#1962]
### Describe the bug

Running `nebari upgrade` fails to find/upgrade included gpu images when searching for tags to upgrade to the current version. Ex: `quay.io/nebari/nebari-jupyterlab-gpu:2023.5.1` will get skipped, but `quay.io/nebari/nebari-jupyterlab:2023.5.1` will trigger an upgrade prompt.

### Expected behavior

All [valid nebari image tags](https://quay.io/organization/nebari) should be matched and trigger the associated upgrade behavior.

### OS and architecture in which you are running Nebari

Ubuntu Linux, x64

### How to Reproduce the problem?

Run `nebari upgrade -c nebari-config.yaml` on a file with something like the following present:

``` yaml

project_name: test
provider: local
domain: test.example.com
namespace: dev
nebari_version: 2023.4.1
profiles:
  jupyterlab:
  - display_name: test
    kubespawner_override:
      image: quay.io/nebari/nebari-jupyterlab:2023.4.1
  - display_name: test-gpu
    kubespawner_override:
      image: quay.io/nebari/nebari-jupyterlab-gpu:2023.4.1

```

### Command output

``` yaml

project_name: test
provider: local
domain: test.example.com
namespace: dev
nebari_version: 2023.7.2
profiles:
  jupyterlab:
  - display_name: test
    kubespawner_override:
      image: quay.io/nebari/nebari-jupyterlab:2023.7.2
  - display_name: test-gpu
    kubespawner_override:
      image: quay.io/nebari/nebari-jupyterlab-gpu:2023.4.1

```

### Versions and dependencies used.

Nebari: 2023.7.2.dev

### Compute environment

None
