### ISSUE TITLE
[ENH] Keycloak theme customization 

### ISSUE THREAD

**Issue by viniciusdc** [nebari-dev/nebari#1980]
We've been wanting this for a while, enabling users to customize the keycloak base themes. 

I am proposing the following config options in the yaml file to easily add new themes to keycloak:
```yaml
theme:
  keycloak:
    repository_url: https://github.com/***/keycloak-custom-theme.git
    repository_branch: master
```

Keycloak has support for `initContainers` configuration, and this would be used to run. [git-sync](https://github.com/kubernetes/git-sync) to clone the repo under a temp location in the pod and move the contents of the custom themes under Keycloak's theme directory by using a shared volume mount. 

I have this implemented in a fork, I will be raising a PR once I do some cleaning and move it to work with the plugin system (still using the previous layout)
