### ISSUE TITLE
Allow users to modify the Keycloak PVC size

### ISSUE THREAD

**Issue by chrislevn** [nebari-dev/nebari#2031]
### Describe the bug

Hi Nebari Dev team, 

I was trying to deploy Nebari with an existing Kubernetes config. I stuck at step 05: `kubernetes-keycloak`. It shows that the minimum persistent volume claim requirement is 40GB, how can I override my nebari-config to pass the keycloak stages? 

Our config file looks like this:

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <CERTIFICATE_AUTH_DATA>
    server: <SERVER>
  name: <NAME>
contexts:
- context:
    cluster: <CLUSTER>
    user: admin
  name: <NAME>
current-context: <CONTEXT>
kind: Config
preferences: {}
users:
- name: admin
  user:
    client-certificate-data: <CLIENT_CERT_DATA>
    client-key-data: <CLIENT_KEY_DATA>
```

Many thanks

### Expected behavior

- Get passed the keycloak stages or all stages in deployment. Ready to be tested locally first. 

### OS and architecture in which you are running Nebari

MacOS M1

### How to Reproduce the problem?

1. Init: 
Run `nebari init existing --project-name <project> --domain-name <domain>
--namespace <namespace> --auth-provider github --terraform-state local
--kubernetes-version  --ssl-cert-email <email>`

2. Deployment: 
Run `nebari deploy -c nebari-config.yaml --disable-checks`
(I wanted to skip taking IP address from the load balancer for the domain, which is currently being used so not ready yet)

### Compute environment

None

**Comment by iameskild** [comment]
Hi @chrislevn, thank you for reaching out! Deploying Nebari to an existing Kubernetes is definitely possible and deploying Nebari to a cloud provided Kuberentes cluster from a Mac (apple silicon or x86) should also work. 

Can you please share your `nebari-config.yaml`? 

Also, while we do allow users to deploy with `--disable-checks`, this is a little less reliable as we can't confirm if the previous stage was deployed correctly.

**Comment by chrislevn** [comment]
Hi @iameskild 

I'm deploying to a Cloud-provided Kubernetes. Here is the `nebari-config.yaml`

```yaml
project_name: <project_name>
provider: existing
domain: <domain>
certificate:
  type: lets-encrypt
  acme_email: <acme_email>
  acme_server: https://acme-v02.api.letsencrypt.org/directory
security:
  authentication:
    type: GitHub
    config:
      client_id: <client_id>
      client_secret: <client_secret>
  keycloak:
    initial_root_password: <password>
    # overrides:
      # postgresql:
      #   # If `true`, the Postgresql dependency is enabled
      #   enabled: true
      #   # PostgreSQL User to create
      #   postgresqlUsername: <sql_username>
      #   # PostgreSQL Password for the new user
      #   postgresqlPassword: <sql_password>
      #   # PostgreSQL Database to create
      #   postgresqlDatabase: <sql_db>
      #   # PostgreSQL network policy configuration
      #   networkPolicy:
      #     enabled: false

default_images:
  jupyterhub: quay.io/nebari/nebari-jupyterhub:2023.7.2
  jupyterlab: quay.io/nebari/nebari-jupyterlab:2023.7.2
  dask_worker: quay.io/nebari/nebari-dask-worker:2023.7.2
storage:
  conda_store: 200Gi
  shared_filesystem: 200Gi
theme:
  jupyterhub:
    hub_title: Nebari - cqai
    hub_subtitle: Your open source data science platform, hosted
    welcome: Welcome! Learn about Nebari's features and configurations in <a href="https://www.nebari.dev/docs">the
      documentation</a>. If you have any questions or feedback, reach the team on
      <a href="https://www.nebari.dev/docs/community#getting-support">Nebari's support
      forums</a>.
    logo: https://raw.githubusercontent.com/nebari-dev/nebari-design/main/logo-mark/horizontal/Nebari-Logo-Horizontal-Lockup-White-text.svg
    display_version: true
helm_extensions: []
monitoring:
  enabled: true
argo_workflows:
  enabled: true
kbatch:
  enabled: true
cdsdashboards:
  enabled: true
  cds_hide_user_named_servers: true
  cds_hide_user_dashboard_servers: false
terraform_state:
  type: local
namespace: cqai-hub
nebari_version: 2023.7.2
existing:
  node_selectors:
    general:
      key: kubernetes.io/os
      value: linux
    user:
      key: kubernetes.io/os
      value: linux
    worker:
      key: kubernetes.io/os
      value: linux
profiles:
  jupyterlab:
  - display_name: Small Instance
    description: Stable environment with 2 cpu / 8 GB ram
    default: true
    kubespawner_override:
      cpu_limit: 2
      cpu_guarantee: 1.5
      mem_limit: 8G
      mem_guarantee: 5G
  - display_name: Medium Instance
    description: Stable environment with 4 cpu / 16 GB ram
    kubespawner_override:
      cpu_limit: 4
      cpu_guarantee: 3
      mem_limit: 16G
      mem_guarantee: 10G
  dask_worker:
    Small Worker:
      worker_cores_limit: 2
      worker_cores: 1.5
      worker_memory_limit: 8G
      worker_memory: 5G
      worker_threads: 2
    Medium Worker:
      worker_cores_limit: 4
      worker_cores: 3
      worker_memory_limit: 16G
      worker_memory: 10G
      worker_threads: 4
environments:
  environment-dask.yaml:
    name: dask
    channels:
    - conda-forge
    dependencies:
    - python=3.10.8
    - ipykernel=6.21.0
    - ipywidgets==7.7.1
    - nebari-dask ==2023.7.2
    - python-graphviz=0.20.1
    - pyarrow=10.0.1
    - s3fs=2023.1.0
    - gcsfs=2023.1.0
    - numpy=1.23.5
    - numba=0.56.4
    - pandas=1.5.3
    - pip:
      - kbatch==0.4.1
  environment-dashboard.yaml:
    name: dashboard
    channels:
    - conda-forge
    dependencies:
    - python=3.10
    - cdsdashboards-singleuser=0.6.3
    - cufflinks-py=0.17.3
    - dash=2.8.1
    - geopandas=0.12.2
    - geopy=2.3.0
    - geoviews=1.9.6
    - gunicorn=20.1.0
    - holoviews=1.15.4
    - ipykernel=6.21.2
    - ipywidgets=8.0.4
    - jupyter=1.0.0
    - jupyterlab=3.6.1
    - jupyter_bokeh=3.0.5
    - matplotlib=3.7.0
    - nebari-dask==2023.7.2
    - nodejs=18.12.1
    - numpy
    - openpyxl=3.1.1
    - pandas=1.5.3
    - panel=0.14.3
    - param=1.12.3
    - plotly=5.13.0
    - python-graphviz=0.20.1
    - rich=13.3.1
    - streamlit=1.9.0
    - sympy=1.11.1
    - voila=0.4.0
    - pip=23.0
    - pip:
      - streamlit-image-comparison==0.0.3
      - noaa-coops==0.2.1
      - dash_core_components==2.0.0
      - dash_html_components==2.0.0
```
