### ISSUE TITLE
[ENH] - Add Loki for logs aggregation

### ISSUE THREAD

**Issue by aktech** [nebari-dev/nebari#2104]
### Feature description

Add Grafana Loki to Nebari configuration.

### Value and/or benefit

Currently the logs are not stored anywhere and it's hard to traverse, find and search in it. It would be great to add Grafana Loki to the Nebari K8s cluster for everything logs.

### Anything else?

The instructions for installing the Helm chart can be found here: 
https://grafana.com/docs/loki/latest/setup/install/helm/#install-grafana-loki-with-helm

**Comment by dharhas** [comment]
cc: @viniciusdc didn't you do this for a client.

**Comment by viniciusdc** [comment]
Yes, I set it up using MiniIO as the storage backend though after using it for a bit I would recommend using an S3 bucket for the log storage. I set it up using the extension mechanism, here are the yaml contents:
```yaml
  - name: loki
    chart: loki
    repository: https://grafana.github.io/helm-charts
    version: 5.8.4
    overrides:
      loki:
        auth_enabled: false
        server:
          http_listen_port: 3100
      minio:
        enabled: true
      test:
        enabled: false
      monitoring:
        dashboards:
          enabled: false
        selfMonitoring:
          enabled: false
          grafanaAgent:
            installOperator: false
        lokiCanary:
          enabled: false
      write:
        replicas: 2
      read:
        replicas: 1
      backend:
        replicas: 1
  - name: promtail
    chart: promtail
    version: 6.11.5
    repository: https://grafana.github.io/helm-charts
    overrides:
      config:
        serverPort: 3101
        lokiAddress: http://loki-gateway/loki/api/v1/push
```
obs. If you get issues with installing on Nebari due to resource conflicts for Minio, the issue might be a conflicting name with the already existing PVC mount that conda-store uses, as they defaults to the same name unfortunately
