### ISSUE TITLE
[BUG] - Fix link to Conceptual guides

### ISSUE THREAD

**Issue by nkaretnikov** [nebari-dev/nebari#2106]
### Describe the bug

> For a more detailed cost estimate, please also refer to our [Conceptual guides] for more information regarding the basic infrastructure provided by Nebari.

https://www.nebari.dev/docs/how-tos/nebari-azure

### Expected behavior

A hyperlink instead of "Conceptual guides"

### OS and architecture in which you are running Nebari

-

### How to Reproduce the problem?

-

### Compute environment

None

**Comment by nkaretnikov** [comment]
Another one:

https://www.nebari.dev/docs/how-tos/domain-registry/#automatic-dns-provision

```yaml
dns:
  provider: cloudflare
  auto-provision: true  
```

Needs to be (note the underscore):

```yaml
dns:
  provider: cloudflare
  auto_provision: true
```
