### ISSUE TITLE
[BUG] - AWS resource group doesn't follow the project-namespace convention

### ISSUE THREAD

**Issue by sblair-metrostar** [nebari-dev/nebari#2139]
### Describe the bug

It seems that everything created in AWS by Nebari follows the project-namespace naming convention except for the [resource group](https://github.com/nebari-dev/nebari/blob/efc291339c113cd244eed4778272e77d8026b0c0/src/_nebari/stages/infrastructure/template/aws/modules/accounting/main.tf#L2). Assuming this convention was established to allow for multiple environments with the same project name but different namespaces to co-exist, this exception creates a conflict when deploying the second.

### Expected behavior

Should be able to create two environments of the same project with different namespaces in AWS.

### OS and architecture in which you are running Nebari

Linux, x64

### How to Reproduce the problem?

Create two Nebari AWS deployments in the same account with the following configurations:

```yaml
provider: aws
namespace: one
nebari_version: 2023.11.1
project_name: <project name>
```

```yaml
provider: aws
namespace: two
nebari_version: 2023.11.1
project_name: <project name>
```

### Command output

```bash session
[terraform]: ╷
[terraform]: │ Error: error creating resource group: BadRequestException: Cannot create group: group already exists
[terraform]: │ 
[terraform]: │   with module.accounting.aws_resourcegroups_group.main,
[terraform]: │   on modules/accounting/main.tf line 1, in resource "aws_resourcegroups_group" "main":
[terraform]: │    1: resource "aws_resourcegroups_group" "main" {
[terraform]: │
```

### Versions and dependencies used.

Nebari: 2023.11.1

### Compute environment

AWS
