### ISSUE TITLE
[ENH] - Set minimum nodes to 0 for AWS deployment

### ISSUE THREAD

**Issue by aktech** [nebari-dev/nebari#2154]
### Feature description

We need to set the `min_nodes` for AWS to **0** for `user` and `worker` nodes. We do have [0 for GCP](https://github.com/nebari-dev/nebari/blob/efc291339c113cd244eed4778272e77d8026b0c0/src/_nebari/stages/infrastructure/__init__.py#L329).

Otherwise this makes Nebari quite expensive (**~$625/month**) for someone trying it with default configuration:

```yaml
amazon_web_services:
  kubernetes_version: '1.26'
  region: us-east-1
```

Cost:

- general node: m5.2xlarge at $0.384/hr: 0.384*720 = $276.48
- user and worker node: 2 x m5.xlarge at $0.192/hr: 2*0.192*720 = $276.48
- Node cost $552.96
- K8s base cost ~ $72

Nebari base cost on AWS: **$625** per month with default config

This was not supported in by AWS, but its been a while [since it's supported](https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-kubernetes-version-1-24/).

### Value and/or benefit

Reduction in base cost for Nebari on AWS with the default configuration.

**Comment by pt247** [comment]
To replicate this, I created a Nebari cluster. The following nodes were created:
```
┌───────────────────────────────────────────────────────── Nodes(all)[1] ──────────────────────────────────────────────────────────┐
│ NAME↑                                           STATUS     ROLE        TAINTS     VERSION                       PODS AGE         │
│ ip-10-10-41-202.eu-west-1.compute.internal      Ready      <none>      0          v1.26.10-eks-e71965b             0 132m        │

└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

Default settings create a single node. All the pods are deployed on the same node. 
Do we still need this change? Am I looking in the right place?

**Comment by pt247** [comment]
Thanks @aktech for pointing out that k9 is not actually showing all the hosts. On AWS EC2 console we see 3 instances.
 
<img width="1324" alt="Screenshot 2023-12-22 at 13 31 03" src="https://github.com/nebari-dev/nebari/assets/8033215/41c84d11-7b04-4a46-ae79-f342d7172047">

After setting the worker and user nodes to 0 and destroying and recreating, I can verify that there is only one general instance.
<img width="1079" alt="Screenshot 2023-12-22 at 14 39 16" src="https://github.com/nebari-dev/nebari/assets/8033215/322112b2-6842-4455-b489-1995b5c31b45">

**Comment by pt247** [comment]
Terraform refuses to create tags for autoscaling groups, only available once the node groups are formed.

**Comment by pt247** [comment]
**Please note**: I had to move the user scheduler to the general node, as it kept the user node alive even if there was no user activity. 

If needed I can raise a separate mini-pr to just do this.

**Comment by pt247** [comment]
To replicate the issue of local deployment, I am trying to run the same config on my laptop. It's an Intel-based Mac. 

### Config
#### Nebari config
I got the following config from the CI logs 
```bash
$ cat nebari-config.yaml 
provider: local
namespace: dev
nebari_version: 2024.1.1rc2.dev82+g99d4445c
project_name: thisisatest
domain: github-actions.nebari.dev
ci_cd:
  type: none
terraform_state:
  type: remote
security:
  keycloak:
    initial_root_password: foad9omyohtfc7hfanwbem8zhahaup3s
  authentication:
    type: password
theme:
  jupyterhub:
    hub_title: Nebari - thisisatest
    welcome: Welcome! Learn about Nebari's features and configurations in <a href="https://www.nebari.dev/docs/welcome">the
      documentation</a>. If you have any questions or feedback, reach the team on
      <a href="https://www.nebari.dev/docs/community#getting-support">Nebari's support
      forums</a>.
    hub_subtitle: Your open source data science platform, hosted
```

#### Hosts file
```bash
$ cat /etc/hosts | grep 172.18.1.100
172.18.1.100 github-actions.nebari.dev
```

#### Error
```bash
[terraform]: Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
[terraform]: 
[terraform]: Outputs:
[terraform]: 
[terraform]: load_balancer_address = {
[terraform]:   "hostname" = ""
[terraform]:   "ip" = "172.20.1.100"
[terraform]: }
Attempt 1 failed to connect to tcp tcp://172.20.1.100:80
Attempt 2 failed to connect to tcp tcp://172.20.1.100:80
Attempt 3 failed to connect to tcp tcp://172.20.1.100:80
Attempt 4 failed to connect to tcp tcp://172.20.1.100:80
Attempt 5 failed to connect to tcp tcp://172.20.1.100:80
Attempt 6 failed to connect to tcp tcp://172.20.1.100:80
Attempt 7 failed to connect to tcp tcp://172.20.1.100:80
Attempt 8 failed to connect to tcp tcp://172.20.1.100:80
Attempt 9 failed to connect to tcp tcp://172.20.1.100:80
Attempt 10 failed to connect to tcp tcp://172.20.1.100:80
ERROR: After stage=04-kubernetes-ingress unable to connect to ingress host=172.20.1.100 port=80
```

### Issue
Nothing is running on port 80 on my laptop. 
```bash
$ sudo lsof -i -P | grep LISTEN | grep :80
Password:
$
```

### Next step
The document clearly says it doesn't work on Mac. So, I will try this on an EC2 machine instead.

**Comment by kcpevey** [comment]
Reopening this as a release blocker as we've discovered an issue. 

From @kenafoster :

>I confirmed it works with the out-of-the-box config so it's the way we are using profile->node selectors that doesn't work with default 0.

He is currently on PTO until next week so we'll wait until then to discuss.

**Comment by rsignell** [comment]
@kcpevey, glad you are on the case!   Really hoping to see this land, as it would help me sell Nebari a lot easier!

**Comment by kenafoster** [comment]
@pt247 shared this with me.  I tested a similar configuration in AWS and it works - you can scale from 0->1 using the "dedicated" selector to target a node pool by name.

So, the way to target different JupyterLab profile to a specific NodeGroup is by using the following key:
```
        node_selector:
          "dedicated": "fly-weight"
```
"`dedicated`" is a key used in lables that Nebari uses for hinting which links ASG to NodeGroups.
And "`fly-weight`" is the name of the node group.

```
The full config looks like this:
amazon_web_services:
  region: eu-west-1
  kubernetes_version: '1.26'
  node_groups:
    general:
      instance: m5.2xlarge
      min_nodes: 2
      max_nodes: 5
    user:
      instance: m5.xlarge
      min_nodes: 0
      max_nodes: 50
      single_subnet: false
    worker:
      instance: m5.xlarge
      min_nodes: 0
      max_nodes: 50
      single_subnet: false
    fly-weight:
      instance: m5.xlarge
      min_nodes: 0
      max_nodes: 50
      single_subnet: false
    middle-weight:
      instance: m5.2xlarge
      min_nodes: 0
      max_nodes: 50
      single_subnet: false
    heavy-weight:
      instance: g4dn.xlarge
      min_nodes: 0
      max_nodes: 50
      single_subnet: false
profiles:
  jupyterlab:
    - display_name: Small Instance
      description: Stable environment with 1.5-2 cpu / 6-8 GB ram
      default: true
      kubespawner_override:
        cpu_limit: 2
        cpu_guarantee: 1.5
        mem_limit: 8G
        mem_guarantee: 6G
        node_selector:
          "dedicated": "fly-weight"
    - display_name: Medium Instance
      description: Stable environment with 1.5-2 cpu / 6-8 GB ram
      kubespawner_override:
        cpu_limit: 4
        cpu_guarantee: 2
        mem_limit: 12G
        mem_guarantee: 8G
        node_selector:
          "dedicated": "middle-weight"
    - display_name: G4 GPU Instance 1x
      description: 4 cpu / 16GB RAM / 1 Nvidia T4 GPU (16 GB GPU RAM)
      kubespawner_override:
        image: quay.io/nebari/nebari-jupyterlab-gpu:2024.1.1
        cpu_limit: 4
        cpu_guarantee: 3
        mem_limit: 16G
        mem_guarantee: 10G
        extra_pod_config:
          volumes:
            - name: "dshm"
              emptyDir:
                medium: "Memory"
                sizeLimit: "2Gi"
        extra_container_config:
          volumeMounts:
            - name: "dshm"
              mountPath: "/dev/shm"
        extra_resource_limits:
          nvidia.com/gpu: 1
        node_selector:
          "dedicated": "heavy-weight"
```
