### ISSUE TITLE
[BUG] - DNS Lookup while deploying often takes time and fails to match LB ip to Domain.

### ISSUE THREAD

**Issue by pt247** [nebari-dev/nebari#2164]
### Describe the bug

While deploying on AWS, the nebari deployment tries to match the IP of the AWS load balancer and the host. The AWS on the other hand gives 2 IPs for the load balancer that it keeps on rotating. For example: 
```
(base)  ➜ nebari-aws (2154-aws-set-minimum-notes-to-0) ✏️  dig a2c6987d8de97475491b592d93537928-2145647921.eu-west-1.elb.amazonaws.com.

; <<>> DiG 9.10.6 <<>> a2c6987d8de97475491b592d93537928-2145647921.eu-west-1.elb.amazonaws.com.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 3748
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;a2c6987d8de97475491b592d93537928-2145647921.eu-west-1.elb.amazonaws.com. IN A

;; ANSWER SECTION:
a2c6987d8de97475491b592d93537928-2145647921.eu-west-1.elb.amazonaws.com. 60 IN A 34.252.157.110
a2c6987d8de97475491b592d93537928-2145647921.eu-west-1.elb.amazonaws.com. 60 IN A 52.214.38.217

;; Query time: 39 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Fri Dec 22 12:31:55 GMT 2023
;; MSG SIZE  rcvd: 132

(base)  ➜ nebari-aws (2154-aws-set-minimum-notes-to-0) ✏️  

```
The above output shows that this domain name resolves to 2 IPs [34.252.157.110, 52.214.38.217].
Below is another dig this time on the hostname it tries to match this with:
```
(base)  ➜ nebari-aws (2154-aws-set-minimum-notes-to-0) ✏️  dig nebari.prashanttiwari.com

; <<>> DiG 9.10.6 <<>> nebari.prashanttiwari.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5851
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;nebari.prashanttiwari.com.     IN      A

;; ANSWER SECTION:
nebari.prashanttiwari.com. 1123 IN      CNAME   a2c6987d8de97475491b592d93537928-2145647921.eu-west-1.elb.amazonaws.com.
a2c6987d8de97475491b592d93537928-2145647921.eu-west-1.elb.amazonaws.com. 60 IN A 34.252.157.110
a2c6987d8de97475491b592d93537928-2145647921.eu-west-1.elb.amazonaws.com. 60 IN A 52.214.38.217

;; Query time: 91 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Fri Dec 22 12:35:11 GMT 2023
;; MSG SIZE  rcvd: 168

(base)  ➜ nebari-aws (2154-aws-set-minimum-notes-to-0) ✏️  

```

The code currently only considers one of these IPs while doing the match to the hostname(the first one). 
Therefore, it keeps on failing to find a match until AWS decides to return the second IP, in which case it passes. 

### Expected behavior

While matching the domain IP with the LB IP, both the available IPS on the domain should be considered. 

### OS and architecture in which you are running Nebari

AWS

### How to Reproduce the problem?

Deploy the default config for AWS.
Redacted config:
```
provider: aws
namespace: dev
nebari_version: 2023.11.2.dev1+gb0c451d1
project_name: nebaridemo
domain: nebari.aaa.com
ci_cd:
  type: none
terraform_state:
  type: remote
security:
  keycloak:
    initial_root_password: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
  authentication:
    type: password
theme:
  jupyterhub:
    hub_title: Nebari - nebaridemo
    welcome: Welcome! Learn about Nebari's features and configurations in <a href="https://www.nebari.dev/docs/welcome">the
      documentation</a>. If you have any questions or feedback, reach the team on
      <a href="https://www.nebari.dev/docs/community#getting-support">Nebari's support
      forums</a>.
    hub_subtitle: Your open source data science platform, hosted on Amazon Web Services
amazon_web_services:
  kubernetes_version: '1.26'
  region: eu-west-1
certificate:
  type: lets-encrypt
  acme_email: aaa@gmail.com
```

### Command output

```bash session
Attempt 8 polling DNS domain=nebari.prashanttiwari.com does not match ip=52.214.38.217 instead got 34.252.157.110
```

### Versions and dependencies used.

Following dependencies were used:

```
(base) ➜ nebari-aws (2154-aws-set-minimum-notes-to-0) ✏️ conda --version
conda 4.8.2
(base) ➜ nebari-aws (2154-aws-set-minimum-notes-to-0) ✏️ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"26+", GitVersion:"v1.26.11-eks-8cb36c9", GitCommit:"3970d4cb523c57bbb0780125446d60f9aca260ad", GitTreeState:"clean", BuildDate:"2023-11-22T21:52:34Z", GoVersion:"go1.20.11", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.26) exceeds the supported minor version skew of +/-1
(base) ➜ nebari-aws (2154-aws-set-minimum-notes-to-0) ✏️
```

### Compute environment

AWS

### Anything else?

We need a small change in the logic of `check_ingress_dns` at [line](https://github.com/nebari-dev/nebari/blob/develop/src/_nebari/stages/kubernetes_ingress/__init__.py#L78C20-L78C20):

```
diff --git a/src/_nebari/stages/kubernetes_ingress/__init__.py b/src/_nebari/stages/kubernetes_ingress/__init__.py
index cabe61f0..1f36f8d4 100644
--- a/src/_nebari/stages/kubernetes_ingress/__init__.py
+++ b/src/_nebari/stages/kubernetes_ingress/__init__.py
@@ -75,15 +75,15 @@ def check_ingress_dns(stage_outputs: Dict[str, Dict[str, Any]], disable_prompt:
     ):
         for i in range(num_attempts):
             try:
-                resolved_ip = socket.gethostbyname(domain_name)
-                if resolved_ip == ip:
+                _, _, ipaddrlist = socket.gethostbyname_ex(domain_name)
+                if ip in ipaddrlist:
                     print(
                         f"DNS configured domain={domain_name} matches ingress ip={ip}"
                     )
                     return True
                 else:
                     print(
-                        f"Attempt {i+1} polling DNS domain={domain_name} does not match ip={ip} instead got {resolved_ip}"
+                        f"Attempt {i+1} polling DNS domain={domain_name} does not match ip={ip} instead got {ipaddrlist}"
                     )
             except socket.gaierror:
                 print(

```

The socket function `gethostbyname_ex`([docs](https://docs.python.org/3/library/socket.html#socket.gethostbyname_ex)) returns a list of IPs. We can find our lookup IP in the list.

This fixes the issue and speeds up the deployment as well.
