### ISSUE TITLE
[ENH] Upgrade argo-jupyter-scheduler to JLab4

### ISSUE THREAD

**Issue by kcpevey** [nebari-dev/nebari#2195]
### Feature description

argo-jupyter-scheduler needs to be upgraded to JLab 4 

External tracking issue: https://github.com/nebari-dev/argo-jupyter-scheduler/issues/4

### Value and/or benefit

It hasn't been tested with JLab4, but chances are high that it will break with the nebari JLab 4 upgrade.

**Comment by kcpevey** [comment]
Assigning @nkaretnikov to this one

**Comment by nkaretnikov** [comment]
@kcpevey No changes are necessary. argo-jupyter-scheduler relies on jupyter-scheduler, which [supports jlab4](https://github.com/jupyter-server/jupyter-scheduler/pull/402).

Tested manually just in case with these images, which use jlab4:

```yaml
default_images:
  jupyterhub: quay.io/nebari/nebari-jupyterhub:2024.1.1rc1
  jupyterlab: quay.io/nebari/nebari-jupyterlab:2024.1.1rc1
  dask_worker: quay.io/nebari/nebari-dask-worker:2024.1.1rc1
```

For reference, the Nebari jlab image is generated via https://github.com/nebari-dev/nebari-docker-images/blob/main/jupyterlab/environment.yaml:

```yaml
  - jupyterlab >=4
...
  - pip:
...
      - argo-jupyter-scheduler==2023.7.1
```

----

@dharhas While we're making a new release, I propose we go ahead and merge https://github.com/nebari-dev/argo-jupyter-scheduler/pull/3 and re-test with it. Compared to argo-jupyter-scheduler on main, this PR introduces important features:
- it generates HTML output files
- notebook and HTML output files are downloadable via the web UI
- send to Slack integration
- logging works and more information is logged.

The version on main:
- only generates notebook output files
- you need to use the terminal to get those
- for scheduled jobs, output files are overwritten on subsequent invocations
- no logs are written to disk.
