### ISSUE TITLE
AWS Private deployments(network)

### ISSUE THREAD

**Issue by ronald50928** [nebari-dev/nebari#2234]
### Context

When doing a private implementation subnets and security groups and other might need to be passed down into the deployment implementation, there minimal AWS guidance on how to achieve this.

### Value and/or benefit

Improving current documentation: https://www.nebari.dev/docs/explanations/custom-overrides-configuration#deployment-inside-a-virtual-private-network

### Anything else?

To create a session that explain a private deployment using AWS:
You can deploy your Nebari environment in an AWS private VPC using the following subnets and security groups. Here is a sample of that confirguration. Using also permissiuons boundary and tagging as a sample:

```
amazon_web_services:
  tags:
    application: "nebari"
    project: "datascience"
    owner: "michael.scott"
    costid: "12345"
  permissions_boundary: arn:aws:iam::1234567890123:policy/<Permissions-Boundary>
  existing_subnet_ids: ["subnet-0c3daad2dc0a12345", "subnet-0962123454112394a"]
  existing_security_group_id: sg-123456787c33c051cc
  kubernetes_version: '1.26'
  region: us-east-1
  node_groups:
    general:
      instance: m5.2xlarge
      min_nodes: 1
      max_nodes: 1
    user:
      instance: m5.xlarge
      min_nodes: 1
      max_nodes: 100
    worker:
      instance: m5.xlarge
      min_nodes: 0
      max_nodes: 450
```

Deployment inside a virtual network is slightly different from deploying inside a public network. As the name suggests, since it's a virtual private network, you need to be inside the network to able to deploy and access Nebari. One way to achieve this is by creating a Virtual Machine (VM) inside the virtual network. Select the virtual network and subnet name under the networking settings of your cloud provider while creating the VM and then follow the usual deployment instructions as you would deploy from your local machine.
