### ISSUE TITLE
[ENH] - Investigate cert-manager

### ISSUE THREAD

**Issue by pavithraes** [nebari-dev/nebari#2238]
### Feature description

We can look into adding cert-manager: https://cert-manager.io

### Value and/or benefit

It'll allow users to get certs from various providers (besides, let's encrypt).

### Anything else?

(Originally proposed by @costrouc)

**Comment by pt247** [comment]
We need to figure out [issuers](https://cert-manager.io/docs/configuration/issuers/) we need to support (other than Let's Encrypt listed as  ACEM). Any votes?

**Comment by pt247** [comment]
The implementation can be broken into several parts, one per Issuer, starting with Let's Encrypt. To resolve this ticket, we should have the following:
1. Figure out list of [issuers](https://cert-manager.io/docs/configuration/issuers/) we need to support to begin with besides.
2. A written road map of how we plan to incorporate Issuers. This should involve documenting any Nebari configuration/CLI changes if needed.
3. Individual tickets for the first few Issuers we intend to support. We should list all high-level changes and dependencies.
4. POC with Traefik (as ingress) + cert-manager (as certificate manager) + Let's Encrypt (as issuer) + http01 (as solver).

**Comment by pt247** [comment]
I tried deploying nebari with the following config:
```
...
...
certificate:
  type: existing
#  acme_email: ptiwari@quansight.com
#  acme_server: https://acme-v02.api.letsencrypt.org/directory
  secret_name: tls-whoami-ingress-http
```

Installed the cert-manager and its CRDs using the following command:
```
helm install cert-manager --namespace dev --version v1.14.4 jetstack/cert-manager --set installCRDs=true 
```

Installed issuer:
```
kubectl apply -f - <<EOF
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
 name: le-quansight-http
 namespace: dev
spec:
 acme:
   email: ptiwari@quansight.com
   server: https://acme-staging-v02.api.letsencrypt.org/directory
   privateKeySecretRef:
     name: quansight-issuer-account-key
   solvers:
     - http01:
         ingress:
           ingressClassName: traefik
EOF
```

Created a certificate:
```
kubectl apply -f - <<EOF
kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: nlb-lab-tls-cert
  namespace: dev
spec:
  commonName: at.quansight.dev
  dnsNames:
    - at.quansight.dev
  duration: 2160h0m0s
  issuerRef:
    name: le-quansight-http
  renewBefore: 360h0m0s
  secretName: tls-whoami-ingress-http
  usages:
    - server auth
    - client auth

EOF
```


I can see that challenge is generated but stuck on 
`Waiting for HTTP-01 challenge propagation: wrong status code '404', expected '200' `

**Comment by pt247** [comment]
I found this in [traefik docs](https://doc.traefik.io/traefik/providers/kubernetes-ingress/)
<img width="1238" alt="Screenshot 2024-05-15 at 18 42 56" src="https://github.com/nebari-dev/nebari/assets/8033215/31ada85c-f995-489a-9743-5dbf9effd0de">
This explains why I could not convince traefik.IngressRoute to auto create certificate. 
I will need to create an temprary endpoint using kubernetes Ingress for initial certificate creation. 

cc: @dcmcand

**Comment by pt247** [comment]
Steps to get cert-manager working: 


1. Start nebaari with following config, note `tls-ingress-http` is set as secret name. 
 
```bash
$ tail nebari-config.yaml
  kubernetes_version: '1.29'
  region: eu-west-1
certificate:
  type: existing
  secret_name: tls-ingress-http
  # acme_email: ptiwari@quansight.com
  # type: lets-encrypt
dns:
  provider: cloudflare
  auto_provision: true
```

2. Install lets-encrypt
```bash
 helm install cert-manager --namespace dev --version v1.14.5 jetstack/cert-manager --set installCRDs=true
```

3. Apply the following config. 
```bash
kubectl apply -f - <<EOF
cat  issuer.yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-manager-cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ptiwari@quansight.com
    privateKeySecretRef:
      name: quansight-issuer-account-key
    solvers:
     - http01:
        ingress:
          class: traefik
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nlb-lab-tls-cert
  namespace: dev
spec:
  commonName: pt.quansight.dev
  secretName: tls-ingress-http
  issuerRef:
    name: cert-manager-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - pt.quansight.dev
EOF
```

**Comment by pt247** [comment]
Certificate configuration in nebari for lets_encrypt.
```yaml
certificate:
  acme_email: ptiwari@quansight.com
  type: lets-encrypt
```

For self-signed certificates: 
```yaml
certificate:
  type: existing
  secret_name: tls-ingress-http
```

Post upgrade to cert-manager. We have a few options:

1. Maintain the same contract in Nebari config but internally use lets-encrypt 
So, the following will use lets-encrypt via the cert-manager.
```yaml
certificate:
  acme_email: ptiwari@quansight.com
  type: lets-encrypt
```
The following configuration will behave exactly as it does today.
```yaml
certificate:
  type: existing
  secret_name: tls-ingress-http
```
2. Explicit another type of certificate. 
```yaml
certificate:
  type: cert-manager:
  issuer: lets-encrypt
  acme_email: ptiwari@quansight.com
```
