### ISSUE TITLE
[BUG] - Notebook Jobs failing because environment is not found

### ISSUE THREAD

**Issue by marcelovilla** [nebari-dev/nebari#2277]
### Describe the bug

When trying to submit a [Jupyter Notebook job](https://www.nebari.dev/docs/tutorials/jupyter-scheduler), the job immediately stops and shows the following error:
```
No such kernel named conda-env-global-global-papermill-py
```

Here is an image of the notebook jobs tab with more information:
![image](https://github.com/nebari-dev/nebari/assets/36754005/0df3cc0f-ecee-42fe-b4d8-27e3065302bc)

### Expected behavior

I would expect the Notebook Job to successfully start and execute.

### OS and architecture in which you are running Nebari

AWS

### How to Reproduce the problem?

I am deploying Nebari from https://github.com/nebari-dev/nebari/commit/a1e5fd1e7262d5193e9c34a55b1c26a8a6fcca8f to AWS, using the following config file:

```yaml
provider: aws
namespace: dev
nebari_version: 2024.1.2.dev44+ga1e5fd1e
project_name: release-test
domain: some.domain.dev
ci_cd:
  type: none
terraform_state:
  type: remote
security:
  keycloak:
    initial_root_password: extra-secure-password
  authentication:
    type: password
theme:
  jupyterhub:
    hub_title: Nebari - release-test
    welcome: Welcome! Learn about Nebari's features and configurations in <a href="https://www.nebari.dev/docs/welcome">the
      documentation</a>. If you have any questions or feedback, reach the team on
      <a href="https://www.nebari.dev/docs/community#getting-support">Nebari's support
      forums</a>.
    hub_subtitle: Your open source data science platform, hosted on Amazon Web Services
amazon_web_services:
  kubernetes_version: '1.26'
  region: us-west-2
monitoring:
  enabled: true
argo_workflows:
  enabled: true
```

### Compute environment

AWS

### Integrations

Argo

### Anything else?

The environment I am using to submit the Notebook Job has `papermill` on it and argo is enabled. This also happens with other environments that have `papermill` on it.
