### ISSUE TITLE
[BUG] - Increase idle culler defaults to 30 min

### ISSUE THREAD

**Issue by Adam-D-Lewis** [nebari-dev/nebari#2508]
### Describe the bug

It's frustrating for users to have the kernel die frequently.  Although this can be overridden in the nebari config I think it's worthwhile increasing the default settings to 30 minutes rather than 15.  This has been a problem for users processing large data sets as well as for local LLM usage where the 15 minute idle culler is frustrating.

BTW, here is how to change the settings in the Nebari config.
```
jupyterlab:
  idle_culler:
    terminal_cull_inactive_timeout: 30
    kernel_cull_idle_timeout: 30
    server_shutdown_no_activity_timeout: 30
```

### Expected behavior

see aboveo

### OS and architecture in which you are running Nebari

Linux x86-64

### How to Reproduce the problem?

see above

### Compute environment

None
