### ISSUE TITLE
[BUG] - Validation error when deploying to Digital Ocean

### ISSUE THREAD

**Issue by karamba228** [nebari-dev/nebari#2530]
### Describe the bug

Deploying a config to Digital Ocean Causes Validation error:

config file:
```
provider: do
namespace: dev
nebari_version: 2024.5.1
project_name: ne8ari-457
ci_cd:
  type: none
terraform_state:
  type: remote
security:
  keycloak:
    initial_root_password: r0hgsbxfdjsibmg62pu8y49jr0bbw2i9
  authentication:
    type: password
theme:
  jupyterhub:
    hub_title: Nebari - ne8ari-457
    welcome: Welcome! Learn about Nebari's features and configurations in <a href="https://www.nebari.dev/docs/welcome">the
      documentation</a>. If you have any questions or feedback, reach the team on
      <a href="https://www.nebari.dev/docs/community#getting-support">Nebari's support
      forums</a>.
    hub_subtitle: Your open source data science platform, hosted on Digital Ocean
digital_ocean:
  kubernetes_version: 1.28.10-do.0
  region: sfo3
  node_groups:
    general:
      instance: g-8vcpu-32gb
      min_nodes: 1
      max_nodes: 1
    user:
      instance: g-4vcpu-16gb
      min_nodes: 1
      max_nodes: 5
    worker:
      instance: g-4vcpu-16gb
      min_nodes: 1
      max_nodes: 5
```

### Expected behavior

There should be no validation error.

### OS and architecture in which you are running Nebari

windows 11 with WSL

### How to Reproduce the problem?

- Create a config file using Nebari-CLI
- Run ```nebari deploy```

After digitalocean_spaces_bucket is created the deploy process stops with a validation error

### Command output

```bash session
ValidationError: 3 validation errors for DigitalOceanInputVars
node_groups.general
  Input should be a valid dictionary or instance of DigitalOceanNodeGroup [type=model_type, input_value=DigitalOceanNodeGroup(ins...in_nodes=1, max_nodes=1), input_type=DigitalOceanNodeGroup]
    For further information visit https://errors.pydantic.dev/2.4/v/model_type
node_groups.user
  Input should be a valid dictionary or instance of DigitalOceanNodeGroup [type=model_type, input_value=DigitalOceanNodeGroup(ins...in_nodes=1, max_nodes=5), input_type=DigitalOceanNodeGroup]
    For further information visit https://errors.pydantic.dev/2.4/v/model_type
node_groups.worker
  Input should be a valid dictionary or instance of DigitalOceanNodeGroup [type=model_type, input_value=DigitalOceanNodeGroup(ins...in_nodes=1, max_nodes=5), input_type=DigitalOceanNodeGroup]
    For further information visit https://errors.pydantic.dev/2.4/v/model_type
```

### Versions and dependencies used.

conda 24.4.0

Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3

2024.5.1

### Compute environment

Digital Ocean
