### ISSUE TITLE
[BUG] - check of immutable fields errors when providing new `node_groups`

### ISSUE THREAD

**Issue by viniciusdc** [nebari-dev/nebari#2719]
### Describe the bug

When updating your nebari-config.yaml to include an extra new group, this will trigger the `json_diff` method from [`JsonDiff`](https://github.com/nebari-dev/nebari/blob/aed2b926fc1176fa90e4b23e6ee9dc02ca0e861d/src/_nebari/utils.py#L435) class to return a modified version of that schema, which is then parsed within the following section:
https://github.com/nebari-dev/nebari/blob/aed2b926fc1176fa90e4b23e6ee9dc02ca0e861d/src/_nebari/stages/terraform_state/__init__.py#L265-L274

With the following error message (in this example, a new `node_group` called `test` was included in the config):
```shell
  File "/nebari/src/_nebari/stages/terraform_state/__init__.py", line 269, in check_immutable_fields
    bottom_level_schema = functools.reduce(
  File "/nebari/src/_nebari/stages/terraform_state/__init__.py", line 270, in <lambda>
    lambda m, k: getattr(m, k), keys[:-1], self.config
AttributeError: 'dict' object has no attribute 'test'

```
### Expected behavior

- Adding new node_groups without any issues

### OS and architecture in which you are running Nebari

Linux

### How to Reproduce the problem?

You can trigger this behavior in any deployment. For easier reproduction, you can do a local deployment as follows:
-  `nebari init local --project template`
- Include a new node group
- Run render once
- Update the node group with any changes that would trigger the JsonDiff to evaluate it as a state change, e.g:
```yaml
local:
  kube_context:
  node_selectors:
    general:
      key: kubernetes.io/os
      value: linux
    user:
      key: kubernetes.io/os
      value: linux
    worker:
      key: kubernetes.io/os
      value: linux
    test:
      key: kubernetes.io/os
      value: linux2

```

### Compute environment

kind
