### ISSUE TITLE
[ENH] - Automated Release Checklist Process via GitHub Actions

### ISSUE THREAD

**Issue by viniciusdc** [nebari-dev/nebari#2747]
### Feature description

The idea would be to introduce an automated release checklist workflow on Github actions to streamline our release process and minimize manual errors. The main goal is for a maintainer responsible for the release to open the release checklist issue (template), which would then trigger a custom action (whose trigger only runs on such issues) that would:

- Run a local nebari deployment initially to execute all the steps in the list sequentially and also would keep track of these updates on a GitHub comment as part of the original issue (similar to how Netfly does or conda-forge's bot)
- Once all local testing is completed, it could also perform the cloud testing for us, though a maintainer would need to finalize that;
- We can also test the nebari upgrade command as part of the pipeline

If any step fails, maintainers will receive prompt notifications within the issue thread for further investigation. We can utilize the existing `nebari-sensei` account for this purpose, enhancing our confidence in each release and reducing friction when creating release candidates (RCs).

Here is a sample workflow configuration:

```yaml
name: Automatic Release Checklist

on:
  issues:
    types: [opened]
  push:
    tags:
      - 'v*.*.*'
      - 'release-checklist'

jobs:
  release-checklist:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'issues' && 
      contains(github.event.issue.labels.*.name, 'release-checklist') ||
      startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Nebar setup commands (env, init, etc)

      - name: Run Deployment
        run: |
        continue-on-error: true

      - name: Run Upgrade Tests
        run: |
          # Command to test upgrades
        continue-on-error: true

      - name: Update Issue with Results
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = context.issue.number;
            // Fetch and parse the results of each step
            // Update the issue checklist items based on results
            // Post comments for any failures
```

This workflow can extend the proposed changes in issues #2701 and #1883 by creating a more comprehensive upgrade testing path as part of our release process and automating these steps.

### Value and/or benefit

This workflow ensures consistency, enhances reliability and reduces friction when cutting release candidates (RCs).,
