### ISSUE TITLE
[ENH] - Add ability to override jhub-apps configuration

### ISSUE THREAD

**Issue by aktech** [nebari-dev/nebari#2753]
### Feature description

Add option in nebari config under `jhub_apps` to override configuration for jhub-apps, for example:

```yml
jhub_apps:
  enabled: true
  overrides:
    service_workers: 4
    allow_multiple_jupyterlab: true
```

### Value and/or benefit

This will allow users to customize jhub-apps from `nebari-config.yml`, without relying on default values.
