### ISSUE TITLE
[ENH] - Add existing efs (name or fs-id) to configuration

### ISSUE THREAD

**Issue by asmacdo** [nebari-dev/nebari#3054]
### Feature description

We are attempting to deploy Nebari to replace an existing jupyterhub deployment. 

I've found some very helpful info in [this discussion](https://github.com/orgs/nebari-dev/discussions/2559), particularly 

```
amazon_web_services:
  terraform_overrides:
       existing_subnet_ids:
           - subnet-xxxxxxxxxxxxxxxx
           - subnet-yyyyyyyyyyyyyyy
        existing_security_group_id: sg-zzzzzzzzzzzzzzz
```
As far as I can tell, there is no "existing_efs_fs_id" or "existing_efs_name", etc. 

Looking at the template, it looks like Nebari has a specific expectation that it will be creating its own EFS. 

https://github.com/nebari-dev/nebari/blob/70ef14002a4183204e02889c2fbb1cd1a46d954c/src/_nebari/stages/infrastructure/template/aws/main.tf#L70
```tf
# ====================== EFS =========================
module "efs" {
  count  = var.efs_enabled ? 1 : 0
  source = "./modules/efs"

  name = "${local.cluster_name}-jupyterhub-shared"
  tags = local.additional_tags

  efs_subnets         = local.subnet_ids
  efs_security_groups = [local.security_group_id]
}
```

If we have the existing subnets and security groups already configured, as well as jupyterhub config overrides to mount the same way we did on the old systems, then using an existing EFS is the last piece of the puzzle?

## alternative

Could we simply rename our old efs to `${local.cluster_name}-jupyterhub-shared`. This sounds a little scary, hopefully terraform wouldn't delete our data if the metadata is different?

### Value and/or benefit

Anyone with existing Jupyterhub deployments on AWS with EFS that would like to switch to a nebari-based setup could benefit! AFAICT, switching to nebari deployment currently requires a nebari-created EFS, which requires migration of users' persistent data from the old_efs -> nebari_efs. (Multiple TB, costly and slow)
