### ISSUE TITLE
[BUG] - GPUs unavailable on AWS due to unscheduled nvidia-device-plugin DaemonSet

### ISSUE THREAD

**Issue by marcelovilla** [nebari-dev/nebari#3074]
### Describe the bug

Node taints for node groups were introduced in [#2605](https://github.com/nebari-dev/nebari/pull/2605) to enable scale-to-zero functionality. As @Adam-D-Lewis [correctly pointed out](https://github.com/nebari-dev/nebari/pull/2605#issuecomment-2297568799), this change prevents certain DaemonSets from being scheduled on tainted nodes unless they explicitly tolerate the taint. One such affected DaemonSet is `aws_nvidia_installer`, which currently only includes the following tolerations: https://github.com/nebari-dev/nebari/blob/06f527dc2d61c6943a5d9e7387785523e6382e47/src/_nebari/stages/kubernetes_initialize/template/modules/nvidia-installer/aws-nvidia-installer.tf#L61-L70)

As a result, the NVIDIA driver installer is never scheduled on GPU nodes, leaving the drivers uninstalled and the GPUs effectively unusable.

### Expected behavior

The `aws_nvidia_installer` DaemonSet should be scheduled on all GPU nodes, regardless of taints introduced for scale-to-zero functionality. This ensures that the NVIDIA drivers are installed automatically on GPU instances, making GPUs available for workloads.

### OS and architecture in which you are running Nebari

Not relevant

### How to Reproduce the problem?

1. Deploy Nebari to AWS, using the following node group configuration:
```yaml
nebari_version: 2025.6.1
# ...
amazon_web_services:
  # ...
  node_groups:
    # ...
    gpu-t4-x1:
      instance: g4dn.xlarge
      min_nodes: 0
      max_nodes: 5
      gpu: true
profiles:
  jupyterlab:
  - display_name: T4 GPU Instance
    description: Stable environment with 4 cpu / 16 GB ram and 1 T4 GPU / 16 GB GPU memory
    kubespawner_override:
      cpu_limit: 4
      cpu_guarantee: 3
      mem_limit: 16G
      mem_guarantee: 10G
      extra_resource_limits:
        nvidia.com/gpu: 1
      image: quay.io/nebari/nebari-jupyterlab-gpu:2025.6.1
      node_selector:
        "dedicated": "gpu-t4-x1"
```
2. Launch a JupyterLab server with the T4 GPU instance profile
3. Run the following command from a terminal with access to the cluster:
```bash
kubectl get nodes "-o=custom-columns=NAME:.metadata.name,GPU:.status.allocatable.nvidia\.com/gpu"
```

The output will look like this:
```
NAME                                         GPU
ip-10-10-30-220.us-west-2.compute.internal   <none>
ip-10-10-49-2.us-west-2.compute.internal     <none>  # Should be 1!
```

4. From a terminal in the JupyterLab server, run the following command:
```bash
nvidia-smi
```

This will result in `bash: nvidia-smi: command not found`, when it should have printed GPU information.

### Command output

```bash session

```

### Compute environment

AWS
